spring:
  application:
    name: spring-boot-alipay
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/alipay?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.funtl.spring.boot.alipay.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
  servlet:
    context-path: "/pay"



